"""initial

Revision ID: e9c10901aa00
Revises:
Create Date: 2026-08-12 21:37:45.515974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e9c10901aa00"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_response_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "sla_status",
            sa.Enum("normal", "warning", "overdue", name="slastatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.CheckConstraint(
            "first_response_seconds IS NULL OR first_response_seconds >= 0",
            name=op.f("ck_tickets_first_response_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index("ix_tickets_answered_at", "tickets", ["answered_at"], unique=False)
    op.create_index("ix_tickets_created_at", "tickets", ["created_at"], unique=False)
    op.create_index(
        "ix_tickets_open_direction_created",
        "tickets",
        ["direction", "created_at"],
        unique=False,
        postgresql_where=sa.text("answered_at IS NULL"),
    )
    op.create_table(
        "incoming_events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "customer_message",
                "employee_response",
                name="eventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_incoming_events_ticket_id_tickets"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_incoming_events")),
    )
    op.create_index("ix_incoming_events_ticket_id", "incoming_events", ["ticket_id"], unique=False)
    op.create_table(
        "outbox_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column(
            "threshold",
            sa.Enum("normal", "warning", "overdue", name="slastatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("direction", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "sent", name="outboxstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], name=op.f("fk_outbox_notifications_ticket_id_tickets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_notifications")),
        sa.UniqueConstraint("ticket_id", "threshold", name="uq_outbox_ticket_threshold"),
    )
    op.create_index(
        "ix_outbox_status_created", "outbox_notifications", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_status_created", table_name="outbox_notifications")
    op.drop_table("outbox_notifications")
    op.drop_index("ix_incoming_events_ticket_id", table_name="incoming_events")
    op.drop_table("incoming_events")
    op.drop_index(
        "ix_tickets_open_direction_created",
        table_name="tickets",
        postgresql_where=sa.text("answered_at IS NULL"),
    )
    op.drop_index("ix_tickets_created_at", table_name="tickets")
    op.drop_index("ix_tickets_answered_at", table_name="tickets")
    op.drop_table("tickets")
    # ### end Alembic commands ###
